payload:
    - '+.facebook.com'
    - '+.facebook.com.es'
    - '+.facebook.com.vn'
    - '+.facebook.fr'
    - '+.facebook.net'
    - '+.fb.com'
    - '+.fb.me'
    - '+.fbcdn.net'
    - '+.fbsbx.com'
    - '+.licdn.com'
    - '+.tfbnw.net'
    - '+.thefacebook.com'