name: Generate readme

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Pull Changes
        run: git pull

      - name: Generate services lists
        env:
          NO_SKIP: true
        run: |
          chmod +x ./update_readme.sh
          ./update_readme.sh

      - name: Get current date
        id: date
        run: |
          echo "DATE=$(TZ=Europe/Moscow date +'%Y-%m-%dT%H:%M:%S')" >> $GITHUB_ENV

      - name: Commit and Push Changes
        run: |
          git config --local user.email "1570693+SaltyMonkey@users.noreply.github.com"
          git config --local user.name "SaltyMonkey"
          git add .
          git commit -m "Generating README.md ${{ env.DATE }}" -a || echo "No changes to commit"
          git push
